voiceflow/orb-common

- orb.yml
all the build envs are running down build-executor except one job of creator app which are using the node-executor instead.
I've changed there and remove from here
> Remove aws cli installation and added con creator app

- orb.yml
> fix: monorepo add build before release 

- orb.yml
> fix: optional slack success message (VF-982)

- orb.yml
> feat: remove set image from production

- .circleci/config.yml
> Xavier/dev pushes/vf 000

- orb.yml
> fix: force the reinstall within the container on e2e

- orb.yml
**Fixes or implements VF-2657**
Implements [this](https://www.notion.so/voiceflow/CI-CD-System-f80ef4dd66b8407ba23f7a72e097b96d)
> ci: new cicd system

- orb.yml
**Fixes or implements VF-000**
Due to some instabilities, I implemented a retry policy command that will help us a lot on the stability of our CICD process
> feat: add retry policy command

- orb.yml
Adds a new `test_e2e_start_service` job that can be used to start the service under test in an e2e environment (with dependencies such as databases and other services)
> feat: add e2e service start test job (vf-000)

- orb.yml
**Fixes or implements VF-2916**
getting the sem_ver from git instead of npm
> fix: new version of setting SEM_VER

- orb.yml
> feat: new production cluster

- orb.yml
**Fixes or implements DX-39**
Add dependency caching support to monorepo builds
voiceflow/libs#323
> feat: update install for monorepo dependency caching (DX-39)

- .circleci/config.yml
**Fixes or implements IN-302**
Apparently, the filters are needed on all jobs 😠
> fix(ci): filters are required for all jobs (IN-302)

- src/commands/monorepo/monorepo_exec_command.yml
- src/commands/monorepo/monorepo_save_cache.yml
**Fixes or implements IN-383**
remove save cache from turborepo
> fix: remove save cache in turborepo

- src/commands/helm/helm-package-publish-prerelease.yml
- src/jobs/helm/helm-publish-prerelease.yml
- src/scripts/helm/publish-prerelease.sh
**Fixes or implements IN-121**
Adds a job for publishing beta releases of helm charts, allowing the infra team to more easily test changes/updates to charts.
> feat: add helm beta release (IN-121)

- src/jobs/helm/helm-publish-prerelease.yml
- src/scripts/helm/publish-prerelease.sh
- src/scripts/helm/set-beta-version.sh
- src/scripts/helm/update-internal-beta-dependencies.sh
Adds an optional step to update the internal chart dependencies to point to beta versions
> feat: allow updating internal dependencies for beta releases (IN-121)

- src/executors/node/e2e-executor.yml
> fix: upgrade e2e engines

- src/commands/docker/build_push_image.yml
- src/commands/track/update_track.yml
add a new tag per branch that will persist 60 days
> fix: avoid untagged images

- src/commands/aws/clone_s3_assets.yml
- src/commands/yarn/vf_save_cache.yml
- src/jobs/monorepo/monorepo_release.yml
- src/scripts/aws/clone_s3_assets.sh
**Fixes or implements IN-464**
Added more reusable comments
> feat: add more parameteres to clone command (IN-464)

- src/commands/docker/docker_prune.yml
- src/jobs/e2e/test_e2e.yml
- src/scripts/aws/clone_s3_assets.sh
- src/scripts/docker/docker_prune.sh
Added the docker prune command
> feat: added docker prune command

- src/commands/e2e/install_e2e_tools.yml
add the official redis ppa and removing the old one
> fix: redis install

- src/executors/node/node-codegen-executor.yml
add mongo to the codegen image
- voiceflow/platform#269
> feat: add mongo for codegen (vf-000)

- src/jobs/e2e/test_e2e.yml
- src/scripts/docker/docker_prune.sh
**Fixes or implements IN-00**
Remove containers used only for running the e2e and just keeping the docker-compose container to be stored to DLC on Circleci
Fix: docker containers should be removed before the volumes
> feat: e2e docker layer caching improvements

- src/commands/monorepo/monorepo_exec_command.yml
Refactor out `run_on_root` logic from bash
> chore: refactor out run_on_root from bash (IN-000)

- src/commands/aws/add_ip_to_security_group.yml
- src/commands/aws/copy_s3_asset.yml
- src/commands/aws/remove_ip_to_security_group.yml
- src/commands/aws/start_ec2_instance.yml
- src/commands/aws/stop_ec2_instance.yml
- src/commands/docker/docker_login.yml
- src/commands/e2e/extract_cypress_artifacts.yml
- src/commands/track/check_track_exists.yml
- src/scripts/track/check_exists.sh
Refactor some simple scripts to remove templating and extract `check_track_exists` script.
I am leaving scripts of 2 lines or fewer inline, as extracting them obfuscates for very little benefit
Testing here: https://github.com/voiceflow/creator-app/pull/6502
> feat: extract check_track_exists (IN-304)

- .circleci/config.yml
- src/scripts/aws/clone_s3_assets.sh
- src/scripts/docker/docker_prune.sh
- src/scripts/helm/package-publish-charts.sh
- src/scripts/helm/publish-prerelease.sh
- src/scripts/track/check_exists.sh
- src/scripts/track/skip_while_draft.sh
- src/scripts/yarn/check_lock_integrity.sh
- src/scripts/yarn/create_lock.sh
**Fixes or implements IN-305**
Add shellcheck to lint extracted shell scripts
Tested here: https://app.circleci.com/pipelines/github/voiceflow/creator-app/152896/workflows/fe8bbeb2-03c7-4d8d-9bab-ae63c9dc87a5
> ci: add shellcheck (IN-305)

- src/commands/docker/post_image_push_actions.yml
- src/scripts/docker/post_image_push.sh
Extracts script from `post_image_push_actions` command and refactors to improve code and fix lints.
[IN-304]: https://voiceflow.atlassian.net/browse/IN-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: extract post image push actions (IN-304)

- src/commands/docker/build_push_image.yml
- src/scripts/docker/build.sh
- src/scripts/docker/push.sh
Extract the scripts for building and pushing docker images
https://app.circleci.com/pipelines/github/voiceflow/creator-app/153107/workflows/e9682333-8714-4a84-b67f-aba5acb6602f/jobs/619168?invite=true#step-109-1
[IN-304]: https://voiceflow.atlassian.net/browse/IN-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: extract docker build and push scripts (IN-304)

- src/commands/monorepo/stop_if_no_changes.yml
- src/commands/track/update_database_track.yml
- src/scripts/track/update_database_track.sh
- Extracts `update_database_track` script
- Extracts environment from `stop_if_no_changes`
https://app.circleci.com/pipelines/github/voiceflow/database-cli/3673/workflows/5f4f7323-eb25-43c6-bdf2-1f82bb841f92/jobs/9032?invite=true#step-109-178
>  feat: extract update_database_track (IN-304)

- src/commands/track/update_database_track.yml
Forgot to set `BUCKET` env var
> fix: pass in bucket name (IN-304)

- src/commands/e2e/extract_cypress_artifacts.yml
To fix failure here: https://app.circleci.com/pipelines/github/voiceflow/database-cli/3713/workflows/a891aca5-d773-4a31-8316-4c0b2fad7f9f/jobs/9122?invite=true#step-126-4
> fix: remove bad shell arg (IN-304)

- src/commands/utils/delete_branch.yml
- src/commands/yarn/yarn_command.yml
- src/scripts/yarn/run_command.sh
- src/scripts/yarn/run_command_in_container.sh
Extract and refactor `yarn_command`
Run outside of container: https://app.circleci.com/pipelines/github/voiceflow/platform/9205/workflows/48a14c47-9d37-4716-9f86-ee1be176e8ab/jobs/35772?invite=true#step-111-8
Run in container: https://app.circleci.com/pipelines/github/voiceflow/general-runtime/7060/workflows/05498e63-89f6-4ec0-ab01-52c51cae9d52/jobs/16223?invite=true#step-110-29
Parallelism with lock file: https://app.circleci.com/pipelines/github/voiceflow/general-runtime/7060/workflows/05498e63-89f6-4ec0-ab01-52c51cae9d52/jobs/16224
> fix: extract and refactor yarn command (IN-304)

- src/commands/helm/helm-get-modified-charts.yml
- src/commands/utils/check_commit_message.yml
- src/commands/utils/get_changed_files.yml
- src/jobs/helm/validate-chart-version-bump.yml
- src/scripts/helm/get_modified_charts.sh
- src/scripts/helm/validate-chart-version-bump.sh
**Fixes or implements IN-631**
Adds job to validate that chart version has been bumped
- Commit message check with pre-release: https://app.circleci.com/pipelines/github/voiceflow/voiceflow-chart/641/workflows/4db81dfd-1e98-4c6d-aa89-2fe14de3d2a2
- Commit message check without pre-release: 
- Validate charts with missing update: https://app.circleci.com/pipelines/github/voiceflow/voiceflow-chart/642/workflows/ea648da7-9dce-44a4-a850-1b5e580c862d/jobs/647?invite=true#step-103-28
- Validate charts with all updated: https://app.circleci.com/pipelines/github/voiceflow/voiceflow-chart/643/workflows/ba44d217-c846-4582-87cc-5f8e3bd94538/jobs/649?invite=true#step-103-27
> feat: add chart version bump validation (IN-631)

- src/jobs/helm/helm-repo-reindex.yml
**Fixes or implements IN-642**
Add reindex job to reindex repo after publish
- https://app.circleci.com/pipelines/github/voiceflow/voiceflow-chart/717/workflows/d3f083aa-88ae-4199-9622-fa6dd28a06c0/jobs/846?invite=true#step-103-2
> fix: add reindex job (IN-642)

- src/scripts/helm/package-publish-charts.sh
> fix: add force flag back (IN-000)

- src/jobs/e2e/run-e2e-tests.yml
Add parallelism to cypress tests
Before:
After:
> feat: parallelism (IN-608)

- src/jobs/e2e/release-env.yml
- src/jobs/e2e/run-e2e-tests.yml
Extract env deletion to a separate job
> fix: extract env deletion to a separate job (IN-608)

- src/commands/monorepo/set-if-file-changed.yml
- src/commands/monorepo/set-service-data-json.yml
**Fixes or implements IN-606**
Adds the following components:
- `set-service-data-json` command: Gathers metadata for each service and writes it to an array
- `set-if-file-changed` command: Sets env var to true if any of the files changed
> feat: add helper functions for monorepo e2e (IN-606)

- src/commands/monorepo/monorepo_save_cache.yml
- src/jobs/yarn/install_and_build.yml
Allow the caller to override the paths that are cached from a build
> fix: expose paths to cache (IN-707)

- src/commands/old_e2e/extract_cypress_artifacts.yml
- src/commands/old_e2e/init_e2e_docker.yml
- src/commands/old_e2e/init_e2e_machine.yml
- src/commands/old_e2e_setup/setup_vf_creator_app_docker.yml
- src/jobs/e2e/run-e2e-tests.yml
- src/jobs/old-e2e/test_e2e.yml
**Fixes or implements IN-707**
Fix old e2e
> fix: old e2e commit (IN-707)

- src/scripts/yarn/run_command_in_container.sh
Copy all when `package` is `all`
> fix: build all in container (IN-000)

- src/jobs/e2e/prepare-env.yml
- src/jobs/e2e/run-e2e-tests.yml
**Fixes or implements IN-724**
- Gather logs when env preparation fails
- Gather logs when e2e tests succeed or fail
> fix: gather logs when suspend fails (IN-724)

- src/commands/monorepo/set-if-file-changed.yml
Change detection was not working on `platform`, this fixes it by disabling globbing in the script
> fix: change detection

- src/commands/monorepo/set-service-data-json.yml
Add the dockerfile to the pacakge.json to specify custom Dockerfile depending on the service
> feat: add dockerfile field

- src/scripts/helm/get_modified_charts.sh
- src/scripts/helm/validate-chart-version-bump.sh
**Fixes or implements IN-660**
- Included added charts in the list of modified charts
- Fix failure in version check for new charts
> fix: unhandled new charts (IN-660)

- src/commands/helm/helm-add-repos.yml
**Fixes or implements IN-987**
Add external secrets operator chart repo for new dependency
> feat: add eso chart repo (IN-987)

- src/commands/monorepo/monorepo_restore_cache.yml
I intentionally didn't do this in my last PR to keep the branches and master separated. 
But if the system is stable, we can try this.
> fix: use master cache

- src/commands/utils/set-pr-number.yml
**Fixes or implements IN-1122**
Passes in the PR number so that we can use it in the cache key
https://app.circleci.com/pipelines/github/voiceflow/creator-app/175017/workflows/6ca64e55-a61c-401c-b00a-efdbeeb8d926/jobs/761578?invite=true#step-113-718_18
https://app.circleci.com/pipelines/github/voiceflow/creator-app/175018/workflows/8bf536f9-e68d-41f8-9707-61f226a81a18/jobs/761597?invite=true#step-113-718_22
https://app.circleci.com/pipelines/github/voiceflow/creator-app/175028/workflows/c8493bf0-fb8e-4112-93c8-409e1fa9f573/jobs/761625?invite=true#step-113-718_22
https://app.circleci.com/pipelines/github/voiceflow/creator-app/175023/workflows/2bec63a6-3c71-48b3-ba84-0a103f2d0637/jobs/761604?invite=true#step-113-718_22
> feat: add command to get PR number (IN-000)

- src/commands/monorepo/monorepo_restore_cache.yml
- src/commands/monorepo/monorepo_save_cache.yml
- src/commands/utils/set-pr-branch.yml
- src/jobs/yarn/install_and_build.yml
**Fixes or implements IN-1122**
Cache turbo builds based on pr number when possible
https://app.circleci.com/pipelines/github/voiceflow/creator-app/175159/workflows/0498e134-104a-4bce-904d-f10a47f8586a/jobs/762414?invite=true#step-114-718_18
https://app.circleci.com/pipelines/github/voiceflow/creator-app/175160/workflows/00d20c70-6f71-4220-9d46-54a2105dd8cc/jobs/762415?invite=true#step-114-718_48
https://app.circleci.com/pipelines/github/voiceflow/creator-app/175164/workflows/612dbabf-1f67-499c-be70-e3ecba305eb6/jobs/762432?invite=true#step-114-718_48
> feat: cache based on pr number when possible (IN-1122)

- src/executors/node/code-test-executor-node-20.yml
**Fixes or implements DX-861**
Use node v20
> feat: node 20 test container (DX-861)

- src/commands/utils/check_env_var_exists.yml
- src/jobs/utils/check_env_var_exists.yml
**Fixes or implements IN-00**
Adds a command and a job that basically checks if a env var exists
> fix: check env var

- src/@orb.yml
- src/executors/java/java-executor.yml
- src/jobs/monorepo/sonarcloud_scan.yml
> feat: sonar and java 21

- src/commands/yarn/install_node_modules.yml
- src/jobs/yarn/install_and_build.yml
**Fixes or implements PL-672**
Allow yarn/install_and_build to specify container for install phase
Specified the same defaults so it should not affect any builds, only allow for changes by specifying the params
> feat: add param for install node_modules in container (PL-672)

- src/commands/vfcli/vfcli-create-env.yml
Use e2e node group for e2e pipelines
> feat: run e2e envs in the e2e node group

- src/commands/monorepo/set-service-data-json.yml
Add the ability to remove apps from the CICD process:
1. Just by adding the property "cienabled" to false in the package.json in the desired app it will be skipped from CICD
> feat: disable services on ci

- src/commands/docker/buildx_cleanup.yml
- src/commands/docker/docker_run_networked.yml
Add command to be able to run an arbitrary command in docker container attached to secondary service containers network.
- https://github.com/voiceflow/general-runtime/pull/722
> feat: run docker command on shared secondary service network (PL-000)

- src/scripts/track/update_track.sh
Use same default builder name as staged_buildx in update_track step
Use `--cache-from` in update_track as well
> feat: use cache-from in update track when buildx enabled

- src/commands/track/update_track.yml
- src/scripts/docker/staged_buildx.sh
- src/scripts/track/update_track.sh
Add param to update_track to push the cache. We want to be able to push the master build cache to the ECR so that all branches can utilize the latest cache.
> feat: add flag to push cache in update_track (PL-000)

- src/jobs/track/update_track.yml
Missed adding flag to job 
- https://github.com/voiceflow/orb-common/pull/207
- https://github.com/voiceflow/general-runtime/pull/737
> fix: add enable_cache_to to update_track job (PL-000)

- src/scripts/docker/staged_buildx.sh
- src/scripts/track/update_track.sh
CircleCI converts boolean params to integers when passing as env vars to an include script
> fix: cache-to flag check correction for boolean to integer

- src/scripts/track/update_track.sh
add missing repo url to cache ref
> fix: cache-to was missing the repo url and was only tag (PL-000)

- src/commands/monorepo/monorepo_lint_report.yml
- src/jobs/monorepo/monorepo_unit_tests.yml
- src/jobs/monorepo/sonarcloud_scan.yml
Storing test results from unit tests and linting with `eslint`
> feat: store linting and test results

- src/executors/node/node-executor-node-20.yml
add `tag` parameter to executor for re-use and to reference node version 
- https://github.com/voiceflow/infrastructure/pull/655
> feat: allow image tag as parameter for node-executor-node-20 (SEC-4)

- src/jobs/release/release.yml
yarn v3 has a different process for versioning (prerelase) and publishing
If a repo is using yarn v1.x, no changes necessary
If a repo is using yarn v3.x, the repo will require the `versions` plugin (installable through `yarn plugin import version`)
If a repo is using yarn v4.x, it is included as a built in
- https://github.com/voiceflow/database-cli/pull/562
> build(feat): yarn v3 prerelease (SEC-10)

- src/jobs/smoke/run-smoke-tests.yml
> feat: smoke tests parallelism

- src/commands/utils/checkout_shallow_clone.yml
* IN-000
* Revert depth changes
> fix: revert depth changes (IN-000)

- src/jobs/monorepo/monorepo_release.yml
- src/jobs/yarn/install_and_build.yml
* IN-1054
* Do not use shallow clone on mono_repo_release step
> fix: resolve shallow clone failures (IN-1054)

- src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
We missed to re-add the track args argument when we were doing the pooling system
> fix: add the track arg file

- src/jobs/yarn/install_and_build.yml
* IN-1058
* Conditionally use deep clone on build steps 
* Could only test regression.The actual fix will be known after use on a clean PR
> fix: conditionally use shallow clone on builds (IN-1058)

- src/scripts/helm/package-publish-charts-ecr.sh
Fixed ECR URL for private chart ECR repo/ 
> Bug: correct release chart ECR Full URL

- src/jobs/helm/helm-publish-charts-ecr.yaml
- src/jobs/helm/helm-publish-prerelease-ecr.yaml
**Fixes or implements IN-1107**
Improve job name
> feat: improved job names for easy identification

- src/jobs/e2e/waiter.yml
Refactor waiter job, making the sleep duration a parameter
> feat: made sleep duration a parameter

- src/jobs/e2e/waiter.yml
**Fixes or implements IN-1215**
Improve waiter job error reporting
https://app.circleci.com/pipelines/github/voiceflow/creator-app/202875/workflows/73853fb8-717d-4aa4-8157-8a3bd2ec2234
https://app.circleci.com/pipelines/github/voiceflow/creator-app/202875/workflows/73853fb8-717d-4aa4-8157-8a3bd2ec2234/jobs/876863/parallel-runs/0/steps/0-101
> fix: improve error reporting in waiter job

- src/jobs/e2e/waiter.yml
> fix: increase waiter time

- src/commands/vfcli/vfcli-delete-or-release-env.yml
> improve logging in release job

- src/commands/vfcli/vfcli-suspend-env.yml
> fix: adding extra log line to the suspend environment job

- src/commands/vfcli/vfcli-resetdb-free-env.yml
> fix: updated parameter description

- src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
- src/commands/vfcli/vfcli-delete-or-release-env.yml
fixes a condition that creates a env every new pipeline
> fix: condition

- src/commands/vfcli/vfcli-delete-or-release-env.yml
- src/jobs/e2e/release-env.yml
> fix: set reset-db attribute to true

- src/jobs/e2e/collect-e2e-logs.yml
**Fixes or implements IN-1332**
> Feat: Group Kubernetes events (IN-1332)

- src/commands/vfcli/vfcli-delete-or-release-env.yml
**Fixes or implements IN-1358**
> fix: Display pipeline URL after triggering env-release-system (IN-1358)

- src/commands/vfcli/vfcli-resetdb-free-env.yml
**Fixes or implements IN-1445**
Switch order of DB reset 
> fix: switched order of DB reset and added sleep

- src/jobs/e2e/prepare-env.yml
This should speed things up because CircleCI images will be more readily available on the workers
> feat: Use new node image for prepare-env step

- src/jobs/release/release_golang.yml
> fix: added a step in relase goland job to install dependencies

- src/commands/vfcli/vfcli-delete-or-release-env.yml
- src/jobs/e2e/release-env.yml
Added force attributes to release env job
> fix: updated force attributes to release env

- src/commands/vfcli/vfcli-delete-or-release-env.yml
> fix: remove force from deletion command

- src/scripts/track/update_track.sh
Accidentally delete the lines to source track status, no tracks are being made
> fix: re-add accidentally removed track status sourcing (IN-1746)

- src/executors/golang/go-executor.yml
Bump up resource class for go-executor and made it accept parameters
> fix: bump up resource class for go-executor

- src/jobs/smoke/run-smoke-tests.yml
* Linear ticket [IN-1370](https://linear.app/voiceflow/issue/IN-1370/upgrade-kubernetes-clusters-from-v127-to-v130) 
* Update subdomain to latest clusters 
> fix: update dev subdomain:IN-1370

- src/scripts/track/update_track.sh
fix: remove trying from gtmq track check
fix: write track to tmp file used elsewhere
> fix: remove trying from gtmq track check

- src/executors/e2e/collector-executor.yml
- src/jobs/e2e/collect-e2e-logs.yml
Add new `collector-executor` using new `ci-collector` image that has `asciinema` and `k9s` deps installed.
Add steps to `collect-e2e-logs` for recording `k9s` with `asciinema` to a gif
> feat: add asciinema collection to collect-e2e-logs (IN-1848)

- src/commands/monorepo/monorepo_integration_tests.yml
- src/jobs/monorepo/monorepo_integration_tests.yml
> fix: integration test command (RUN-499)

- src/commands/aws/invalidate_cloudfront_distribution.yml
- src/jobs/monorepo/monorepo_release.yml
- src/scripts/aws/invalidate_cloudfront_distribution.sh
> feat: add invalidation command

- src/jobs/integration/run-integration-tests.yml
- src/jobs/monorepo/monorepo_lint_report.yml
- src/jobs/monorepo/monorepo_release.yml
**Fixes or implements IN-2279**
avoid pre-releases collisions
> fix: avoid pre-releases colisions

- src/scripts/track/update_track.sh
Use `PACKAGE` for DD_SERVICE Env var as this is what is used for `APP_NAME`
> fix: use PACKAGE instead of COMPONENT for dd service name to match APP_NAME (IN-2388)

- src/executors/node/build-executor.yml
- src/jobs/docker/create_manifest.yml
- src/scripts/docker/create_manifest.sh
Add `docker/create_manifest` job and script to manually create a multiplatform manifest
> feat: add docker/create_manifest job (IN-2735)

- .circleci/config.yml
Use `circleci-cli` to update `COMMON_ORB_VERSION` in `dev-test` context on successful publish of production orb
> feat: update COMMON_ORB_VERSION in dev-test context (IN-2754)

- src/commands/track/promote_production.yaml
- src/jobs/track/promote_production.yaml
- src/scripts/track/promote_production.sh
Promote tags built in master to production, instead of rebuilding
> feat: promote_production pattern (IN-2854)

- src/scripts/track/promote_production.sh
- src/scripts/utils/check_wait_master.sh
use "latest-master" style tags for promote production
> fix(revert): use "latest-master" style tags for promote production (IN-2949)

- src/scripts/utils/check_wait_master.sh
platform avg master run: 18.5 min
creator-app avg master run: 23.5 min
> feat: increase check master timeout to 25 minutes (IN-3060)
