- orb.yml
allow sentry project configuration with a predefined parameter
> fix: add sentryProject param

- orb.yml
**Fixes or implements VF-1849**
Uses hosted container image to install all tooling for e2e tests
Pushed the new e2e docker image to ECR and used it in our e2e executor on CircleCI
> ci: use e2e setup image from ECR

- orb.yml
**Fixes or implements VF-2194**
This updates the skipping behaviour to skip on all new branches (branches without PRs). This does not risk skipping e2e altogether since all PRs are set to be drafts now.
> ci: skip e2e on branches without PRs (VF-2194)

- orb.yml
**Fixes or implements VF-2167**
This adds a new command called `trigger_tags_pipelines` that manually triggers the CircleCI pipelines for tags passed through an environment variable. This is used to trigger the pipelines for tags published by lerna as part of the `release_monorepo` step. This is necessary due to the limitations on payload size for GitHub web hooks.
In order to pass the tags generated as part of the job, an environment variable is used.
Tested:
https://app.circleci.com/pipelines/github/voiceflow/poc-docker-layer-caching/153/workflows/39801740-b9ec-427e-a534-0ffd7965547c/jobs/140
> ci(tags): trigger CircleCI for tags published in release_monorepo (VF-2167)

- orb.yml
run tests using compiled code instead of using `ts-node` or other similar tools (same as when pulled from pre-built containers)
> fix: run e2e tests with built code (vf-000)

- orb.yml
Again, similar to `update_track` we need to explicitly pass the local npm registry URL and connect to the host network in order to use the pre-release packages during docker build.
> fix: use local registry during e2e docker build (vf-000)

- .circleci/config.yml
- .github/release.yaml
- .github/workflows/release.yaml
**Part of IN-306**
Adds a GitHub Actions Workflow to create a new release when changes are pushed to master. This follows the rules of semantic commits, so not all commits will create a new release.
Also updates the CircleCI config to use the new publish command to publish on release.
> ci: add release action on push to master (IN-306)

- .circleci/config.yml
- .gitignore
**Fixes or implements VF-302**
Due to an unintuitive behaviour in CircleCI described [here](https://discuss.circleci.com/t/cant-trigger-workflow-on-git-tag-push-using-when-condition/43252/5), at least one of the jobs in the workflow must filter on tags for CircleCI to trigger based on a tag push.
Also adds a .gitignore
> fix: fix orb deployment with tags (IN-302)

- .circleci/config.yml
**Fixes or implements IN-303**
Refactors deployment code to use pre-steps to extract orb sections from subdirectories.
This means that we no longer need to manually call the pack and validate commands.
We also extract the tags filter for clean reuse
> chore: refactor orb deployment to use pre-steps (IN-303)

- .circleci/config.yml
- src/commands/yarn/authenticate_npm.yml
- src/scripts/yarn/authenticate-npm.sh
**Fixes or implements IN-378**
Use the `.yarnrc.yml` to authenticate Yarn 3
> fix: add yarn3 auth for authenticate npm command (IN-378)

- src/commands/monorepo/monorepo_exec_command.yml
**Fixes or implements IN-381**
Tests were being skipped in staging and then failing on master. This runs those tests on staging.
> ci: run monorepo commands on bors branches (IN-381)

- src/commands/monorepo/monorepo_save_cache.yml
**Fixes or implements IN-383**
Update turborepo caching to persist all of `node_modules` to workspace
By doing this we can avoid re-installing in the `test` job and since `node_modules` already contains the `.cache` turborepo can still use it to speed up the testing phase
- voiceflow/platform#44
> fix: monorepo turborepo caching strategy (IN-383)

- src/commands/monorepo/monorepo_exec_command.yml
This line was causing the yaml linter to complain, so I made it more concise using pattern matching.
> fix: make overlong line more concise

- src/commands/e2e_setup/setup_vf_dbs_docker.yml
Allowing extra args to be passed to database init command so that it can be used to simplify [the config here](https://github.com/voiceflow/platform/blob/master/.circleci/continue-config.yml#L173)
[tested successfully](https://github.com/voiceflow/platform/pull/199/commits/084b8463200c45bb6633bc6d3c3d9d67eb9d2d45)
> feat: add extra args for db init (vf-000)

- src/scripts/aws/clone_s3_assets.sh
Bash needs an explicit `== true` to resolve booleans. Otherwise `export X=false` will result in `if [[ $X ]]; then` being "true".
You can test this in your terminal with a simple script:
```
if [[ $TEST ]]; then
echo "Test is true"
else
echo "Test is false"
fi
```
then run `export TEST=false` and `./test.sh` will result in `"Test is true"`
There are no booleans in bash - just strings and numbers. So it's really just a string that says "false"
https://alexopensource.wordpress.com/2021/03/11/there-are-no-booleans-in-bash-commands/
> fix: s3 bash condition (CT-000)

- src/commands/docker/build_push_image.yml
- src/commands/track/update_database_track.yml
- src/jobs/release/release.yml
- src/jobs/track/update_database_track.yml
If a tag is created or we are running the docker push image on a tag, the SEM_VER variable should be the latest created too.
> fix: set sem_ver with latest tag created

- src/scripts/helm/package-publish-charts.sh
**Fixes or implements IN-305**
Fix the SIGPIPE from `find` in helm publishing
This issue is subtle, but stems from `head -n1` closing its reading pipe while `find` is continuing to produce output. By setting `maxdepth` to `1`, this ensures we only find the one file we want
[IN-305]: https://voiceflow.atlassian.net/browse/IN-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fix helm package publishing (IN-305)

- src/commands/monorepo/monorepo_exec_command.yml
- src/commands/monorepo/monorepo_exec_command_when_package_changed.yml
- src/scripts/monorepo/exec_command.sh
Extract `monorepo_exec_command` and collapse `monorepo_exec_command_when_package_changed`
Tested here:
- With `force_execute`: https://app.circleci.com/pipelines/github/voiceflow/creator-app/153252/workflows/db7ce4ea-98f0-4a75-ab42-d7360a56e273/jobs/620411?invite=true#step-111-84
- Without `force_execute`: https://app.circleci.com/pipelines/github/voiceflow/creator-app/153220/workflows/1a4bfb10-b525-4ba2-b587-8a4ae5d78e01/jobs/620181?invite=true#step-111-48
> feat: extract exec monorepo command (IN-304)

- src/commands/track/update_database_track.yml
- src/jobs/track/update_database_track.yml
When extracting the script, I assumed that all values for `image_tag` and `sem_ver_override` would be passed directly rather than as env var names, but this was not the case. This ended up breaking the flow for updating `database-cli` tracks. 
This PR fixes that by allowing the value for semantic version to be passed in to the job rather than computing it within the job
This will require dyamic config to get the correct value for the semver before running this job.
Tested here: https://app.circleci.com/pipelines/github/voiceflow/database-cli/3581/workflows/a61b5c39-2a76-4fe6-80dc-5a7f95c7e221/jobs/8832
- https://github.com/voiceflow/database-cli/pull/315
> fix: database track update (IN-304)

- src/commands/utils/check_commit_message.yml
- src/commands/utils/sync_branches.yml
I replaced the repeated code in `sync_branches` with a call to `check_commit_message`.
In the end, this doesn't really warrant an extraction after being refactored.
Without commit message match: https://app.circleci.com/pipelines/github/voiceflow/platform/9242/workflows/b2978cca-727e-4c42-85d2-5285f70e260f/jobs/36017?invite=true#step-104-7
With commit message matching (message matched): https://app.circleci.com/pipelines/github/voiceflow/platform/9245/workflows/e8aa269b-af88-4eed-92e8-e21366130130/jobs/36020?invite=true#step-103-4
With commit message matching (message not matched): https://app.circleci.com/pipelines/github/voiceflow/platform/9247/workflows/6b174ab6-1947-4ab5-9065-ca45f07fe105/jobs/36021?invite=true#step-103-8
> fix: refactor sync branches (IN-304)

- src/commands/yarn/yarn_command.yml
- src/scripts/yarn/run_command.sh
- src/scripts/yarn/run_command_in_container.sh
**Fixes or implements IN-583**
Add retries to `yarn_command`
- Run out of container with no retries:
- https://app.circleci.com/pipelines/github/voiceflow/google-service/5821/workflows/3427facb-ea9a-4cc5-96ca-8e45ed63aa62/jobs/11822?invite=true#step-104-23
- Run out of container with retries:
https://app.circleci.com/pipelines/github/voiceflow/google-service/5821/workflows/3427facb-ea9a-4cc5-96ca-8e45ed63aa62/jobs/11823?invite=true#step-109-81
- Run in container with retries:
https://app.circleci.com/pipelines/github/voiceflow/platform/9724/workflows/616988df-4d44-4e5b-a6bc-36f90daecac4/jobs/38548?invite=true#step-119-293
- Run in container without retries:
https://app.circleci.com/pipelines/github/voiceflow/creator-app/155422/workflows/12dcba8f-19c9-4aa5-a193-7be628a411e8/jobs/638819?invi …
> feat: add retries to yarn_command (IN-583)

- src/jobs/release/release.yml
Making the `release` command configurable so it can be run on a sub-directory (`infrastructure-tools/package-scripts`)
> ci: make release script configurable (DX-000)

- src/jobs/release/release.yml
**Fixes or implements IN-608**
Allow the user to specify the version and tag to release instead of relying on `semantic-release` to specify it
> fix: add prerelease tag override for release (IN-608)

- src/commands/e2e/set-env-name.yml
Only use `e2e-abcdef` for env name to keep it short
> fix: name too long (IN-707)

- src/commands/yarn/install_node_modules.yml
- src/jobs/e2e/build-e2e-tests.yml
**Fixes or implements IN-941**
Update flags to not break Yarn 3 builds
Yarn 3
Yarn 1 does not break with `--immutable`
> fix: remove deprecated flag to support yarn 3 (IN-941)

- src/commands/old_e2e_setup/setup_vf_creator_app_machine.yml
creator-app uses yarn 3 which no longer supports --frozen-lockfile
this replicates the changes made here:
https://github.com/voiceflow/orb-common/commit/6399f57e36d0db46569ca6d72594349b3af98f8f
> fix: old e2e tests (CT-000)

- src/jobs/e2e/build-e2e-tests.yml
We've had to lower the concurrency for unit tests already, this is for a docker large instance.
https://github.com/voiceflow/creator-app/blob/2367f7b33fda2ac7027db5ff2bdcc71f6f4b1633/package.json#L105
Just to be safe no more multithreading :)
> fix: lower build e2e test concurrency (CT-000)

- src/jobs/e2e/build-e2e-tests.yml
Bring this in line with the `build` step, which uses `large`:
This way we can just hard code `--concurrency=4` for `yarn build`, for long term stability into `creator-app`
On the other end, we have:
https://github.com/voiceflow/creator-app/pull/7393/files
> fix: use node large executor for build-e2e-test (CT-000)

- src/commands/yarn/vf_save_cache.yml
https://voiceflow.atlassian.net/browse/IN-969
At this stage, I believe we have more people working more often in `yarn 3` based projects (`creator-app` and `platform`) than `yarn 1`. This this will speed the overall company up
The only signficiant ones left are `general-service` and `general-runtime` - it should be the core/platform team that focuses on migrating them to `yarn 3`.
The correct way to cache `yarn 3` is by referencing `/.yarn/cache`. It's actually documented by CircleCI:
https://circleci.com/docs/caching/#basic-example-of-yarn-package-manager-caching
> fix: use yarn cache instead of node modules (IN-696)

- src/commands/monorepo/monorepo_restore_cache.yml
- src/commands/monorepo/monorepo_save_cache.yml
- src/commands/yarn/vf_save_cache.yml
What's going on here:
we are going to use turborepo to cache all the builds. 
we also need to cache `node_modules` ontop of `.yarn/cache` because the linking step often takes up to 1-2 minutes.
We were already caching `node_modules` before so it's not a big deal.
> fix: expiremental turborepo cache (CT-000)

- src/commands/yarn/persist_node_build.yml
- src/jobs/e2e/build-e2e-tests.yml
so it's important that the `.yarn/cache` gets propagated to the `update_service_track` jobs.
Otherwise when creating the docker image, it will reinstall and fetch all the packages again.
This is a nice fix because the cache is ALWAYS generated by the `build` step, so this is a permenant -2 mins to the image building flow. 
The second thing is I put together a hacky cache for the `build-e2e-tests`, it can't use the regular node caches because its inside the `/tmp/e2e-tests` folder instead of `/home/circleci/voiceflow`. We can do a `mv` or something after but that's still hacky.
The `build-e2e-tests` is a bit of a one-off, we can afford to refactor it later.
> fix: persist yarn cache (CT-000)

- src/commands/monorepo/monorepo_restore_cache.yml
- src/commands/monorepo/monorepo_save_cache.yml
- src/jobs/yarn/install_and_build.yml
Pipeline values are not available in orbs, so we can't directly reference `"<< pipeline.git.branch >>"`. Instead, we use mustache templates to conditionally use the branch name or the override
> fix: branch not available in orb components

- src/executors/node/default-executor.yml
- src/jobs/e2e/prepare-env.yml
- src/jobs/e2e/provision-env.yml
- src/jobs/e2e/release-env.yml
- src/jobs/e2e/run-e2e-tests.yml
**Fixes or implements IN-1156**
- Run E2E in brazil by default
- Print pods on failure
- Success https://app.circleci.com/pipelines/github/voiceflow/creator-app/180643/workflows/768b3762-7ef7-421b-b4de-93493d9b11af
- Failed run
https://app.circleci.com/pipelines/github/voiceflow/creator-app/180705/workflows/09db07b6-9ed5-4401-a9b3-b34c3e702c96/jobs/790276
> fix: e2e in brazil (IN-1156)

- src/commands/monorepo/set-service-data-json.yml
- src/commands/utils/compute_base_revision.yml
- src/commands/utils/get_changed_files.yml
**Fixes or implements IN-1116**
- We are noticing that for mono repos, if a PR is not the first in a list of commits to master, when the merge to production is done, the changes for that PR are not being included in the docker images being built.
- The issue was that all branches were comparing their latest changes to the latest master.
- The fix is to use the previous CI pipeline's git revision to get the changed files and if the previous revision is not available 
use the current revision
-  For `staging` and `trying` branches use master as base revision since the PR changes were created from master 
* https://github.com/voiceflow/creator-app/pull/7679
* Base revision for `trying` and `staging` resolves to master
* Current run refers to previous run showing that  base revision for non …
> fix:use correct base revision:IN-1116

- src/commands/utils/compute_base_revision.yml
* IN-1116
* Cater for base branches that expire or when we rebase and the ancestor of current branch changes from what it was.
https://github.com/voiceflow/creator-app/pull/7703
> fix: cater for edge case base branches that dont exist:IN-1116

- src/jobs/smoke/run-smoke-tests.yml
**Fixes or implements DX-988**
Update smoke tests to run in parallel
I had originally thought that it wasn't possible because sorry cypress is no longer supported with cypress 13+
but we found a NEW work around with [cypress-split](https://www.npmjs.com/package/cypress-split) 💪
> feat: make smoke tests run in parallel (DX-988)

- src/commands/utils/compute_base_revision.yml
* https://voiceflow.atlassian.net/browse/IN-1173
* Use correct base revision for branches 
*   For all branches that are created, eg for review envs, normal PR's,branch rebases,bors trying/staging and renovate builds, use master as the base revision; except for production
* Master branch has multiple PR's merged into it independently before the `branch-sync` to production occurs.
* After sync, the 2 branches are a mirror of each other because the current SHA for production is similar to the SHA for master branch
* In the case where the SHA's are the same, we then do a diff between HEAD and HEAD~1, which discards all other changes
* Using latest master as base revision for production would cause us to skip detecting all changes that occured in the multiple PR's merged, causing us to only …
> fix: use correct base revision for branches:IN-1173

- src/commands/track/update_track.yml
- src/executors/lambda/lambda-executor.yml
- src/jobs/track/update_track.yml
- src/scripts/track/update_track.sh
* https://voiceflow.atlassian.net/browse/IN-1175
* function-lambda builds are unstable and this is to rectify that issue 
* Use arm executors and target arm when building 
- https://github.com/voiceflow/orb-common/pull/194/files
- https://github.com/voiceflow/creator-api/pull/1406
- https://app.circleci.com/pipelines/github/voiceflow/function-lambda?branch=edison/stabilize-lambda-function-builds/IN-1175
> fix: use arm executor to stabilize function-lambda build:IN-1175

- src/commands/docker/build_push_image.yml
- src/commands/track/update_track.yml
- src/commands/utils/check_image_exists.yml
- src/commands/yarn/yarn_command.yml
- src/jobs/monorepo/monorepo_schema_validate.yml
- src/jobs/track/update_track.yml
Due to the fact that Circleci is removing ld versions of Linux images, it seems that it will remove old versions of remote docker executors: https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
The recommendation is to use default and edge. I think default is more than enough for now
> fix: switch to default docker

- src/jobs/smoke/run-smoke-tests.yml
**Fixes or implements DX-1559**
Add a `stable-only` flag to the smoke test job which defaults to `true`
When enabled it filters to only run tests in the `cypress/integration/stable/` folder by executing the `test:smoke:stable` job
> feat: add stable-only flag to smoke test job (DX-1559)

- src/commands/docker/staged_buildx.yml
- src/commands/track/update_track.yml
- src/jobs/track/update_track.yml
- src/scripts/docker/staged_buildx.sh
- src/scripts/track/update_track.sh
**Fixes or implements PL-664**
Add step to target a stage of a Dockerfile in buildx
Want to bring forward our usage of Docker/buildkit toolings and features with more control/split ownership of building between dev and infra
Remote Cache Registry:
- Default naming scheme is `<image repo>:cache-<branch>`
- Default cache-from: current branch cache and master cache
- Only allow 1 cache per branch
- likely needs a way to cleanup the remote cache after it's been merged and built on master, if the storage is an issue
DLC:
- Default builder name is `builder-<branch>` as a key
- https://github.com/voiceflow/creator-api/pull/1406
> feat: docker buildx for target stages (PL-664)

- src/scripts/docker/staged_buildx.sh
- src/scripts/track/update_track.sh
CircleCI doesn't like arrays especially when passing to scripts through env vars. pass as string and force cast to array through use of `read -a`
> fix: force EXTRA_BUILD_ARGS from string to array

- src/jobs/monorepo/sonarcloud_scan.yml
I think sonar needs this since the `tsconfig.json` now relies on a dependency that needs to be installed first
> feat: optionall install dependencies before scanning

- src/jobs/release/release.yml
* Linear [ticket](https://linear.app/voiceflow/issue/IN-992/resolve-semantic-release-issues-for-database-cli) 
* Resolve semantic release failures for database-cli repo.
* Propagate and use an ssh key during the build, that has write access 
* https://app.circleci.com/pipelines/github/voiceflow/poc-dbcli-semantic-release/33/workflows/5ca5f28c-5370-4266-a87e-ee7ac068a989
> fix: add ssh key to release job:IN-992

- src/jobs/smoke/run-smoke-tests.yml
Test caching the turborepo build of the smoke test.
No cache:
With cache:
Tested on this PR:
https://github.com/voiceflow/creator-app/pull/8027
> fix: cached smoke tests (IN-1000)

- src/commands/monorepo/monorepo_save_cache.yml
this is a limited solution until turborepo offers a proper way to know which cache actually got used as part of a job 
(we could do a super shitty grep of the output logs, but it's extremely janky)
https://github.com/vercel/turbo/discussions/7450
Just delete all cache files over 7 days old.
Tested this on an ssh'ed container, goes from 2.4GB -> ~150MB.
We also don't need to persist turborepo to the workspace.
> fix: clear turborepo cache (IN-1002)

- src/jobs/smoke/run-smoke-tests.yml
I realized with circleci's caching system, once `smoke-test-build-cache` is set, it will never be cleared again.
So even if there is a new build and the cache changed, it will not save anything. 
Instead we need to use the commit SHA of the smoke-test git project as a marker for the cache.
Tested on this branch in creator-app:
https://github.com/voiceflow/creator-app/pull/8049
I have to save the commit into a file and use the checksum. Reference relevant files:
https://devops.stackexchange.com/questions/9147/how-to-get-other-than-no-value-when-interpolating-environment-some-var/9177
https://discuss.circleci.com/t/interpolating-environment-some-var-after-setting-some-var-results-in-no-value/32352
https://discuss.circleci.com/t/setting-environment-variable-from-script-command-for-later-use-i …
> fix: tie to commit hashes (IN-1000)

- src/commands/yarn/vf_save_cache.yml
- src/jobs/smoke/run-smoke-tests.yml
This is recommended by cypress:
https://docs.cypress.io/guides/continuous-integration/introduction#Caching
There are some issues if we don't cache it. Tested on:
https://github.com/voiceflow/automated-testing/pull/167
> fix: cache cypress build (IN-1004)

- src/commands/utils/checkout_shallow_clone.yml
* Linear [IN-1006 ](https://linear.app/voiceflow/issue/IN-1006/use-shallow-clone-instead-of-checkout)
* We can speed up builds by up to and shave off 30 seconds, eg for repos like creator-app 
* Where it takes 30 seconds to clone, it will now take 1 second 
* Do shallow clones for both branches and tags 
*  [ notion link](https://www.notion.so/voiceflow/Shallow-clone-across-all-repos-9e4f6402bcbe4f3f925f583c61c0ec82)
> fix: resolve linting issues (IN-1006)

- src/commands/track/update_track.yml
* Linear [ticket](https://linear.app/voiceflow/issue/IN-1006/use-shallow-clone-instead-of-checkout) 
* Dont use shallow cloning for track updates
* Track updating checks tags and branches and needs to do several comparisons in its logic 
* We are noticing intermittent failures when some of the tags that have been pulled don't have corresponding commits 
- circle-ci [build](https://app.circleci.com/pipelines/github/voiceflow/creator-app/196117/workflows/91c5f140-2eb3-4108-86fc-1396948ac64d/jobs/851702)
> fix: dont use shallow cloning for track  updates (IN-1006)

- src/commands/utils/checkout_shallow_clone.yml
We have a shallow repository with only a single commit. We can verify by executing git rev-parse --is-shallow-repository.
HEAD^ points to the commit before our current commit – which does not exist in shallow clones of depth 1 and sometimes it does not exist in depth 2. We have to unshallow we clone or deepen it to include the commits which we are referencing.
For instance, to deepen our shallow clone to include the latest 10 commits, run git fetch --depth=10
https://github.com/voiceflow/creator-app/pull/8107
> fix: checkout last 10 commits

- src/commands/utils/checkout_shallow_clone.yml
* Linear [ticket](https://linear.app/voiceflow/issue/IN-1054/resolve-shallow-clone-issue-causing-creator-app-tests-to-fail) 
* Checkout PR branches at depth 2 as some of our git diff logic requires HEAD^ 
* https://github.com/voiceflow/creator-app/pull/8111
> fix: use depth 2 on PR branches as well (IN-1054)

- src/commands/track/update_track.yml
- src/executors/node/build-executor.yml
- src/jobs/track/update_track.yml
- src/scripts/track/update_track.sh
allow image push from build instead of converting and loading into docker locally
`cosign` with remote manifests on digest instead of labels
relies on `ci-image:25.0.5-dind-vf-2` , so will need additional monitoring on `update-track` runs 
- https://github.com/voiceflow/infrastructure/pull/668
- https://github.com/voiceflow/infrastructure/pull/670
- https://github.com/voiceflow/infrastructure/pull/671
Used in `VFML`:
- https://github.com/voiceflow/VFML/pull/623
successful builds in:
* [event-ingestion-service](https://github.com/voiceflow/event-ingestion-service/pull/62)
* [general-service](https://github.com/voiceflow/general-service/pull/580)
* [platform](https://github.com/voiceflow/platform/pull/1025)
* [general-runtime](https://github.com/voiceflow/general-runtime/pull/820)
* …
> feat(update-track): allow push from build and cosign with manifests (PL-1056)

- src/jobs/e2e/waiter.yml
Noticed that it could take sometime before the next job in a pipeline starts. The waiter job currently sleeps for 1sec before checking again
If a job expected to run in the pipeline doesn't run in that 1second window, waiter sees the pipeline as completed
> fix: increase the sleep time before it checks running jobs

- src/jobs/e2e/collect-e2e-logs.yml
* [IN-1101](https://linear.app/voiceflow/issue/IN-1101/improve-logs-in-our-cicd-system)
* https://app.circleci.com/pipelines/gh/voiceflow/general-runtime/16323/workflows/7dc9898c-138b-4b7e-a71d-b2e206b4c216
* The change allows us to 
* Capture component logs during a smoke test run 
* Logs are `tailed` for the duration of the smoke test run allowing us to preserve logs from initial pod instance if a 
pod restart occurs
* Capture summary pod state for all pods before smoke test run 
* Capture summary pod state for all pods after smoke test run 
* Capture detailed pod state for each pod after smoke test run 
*  Use a separate job that runs in parallel to smoke tests job so that we can capture the 8 parallel smoke test run logs as 
an aggregate  
* Use stern for log tailing instead of normal …
> feat: improve smoke tests visibility (IN-1101)

- src/jobs/e2e/collect-e2e-logs.yml
* https://linear.app/voiceflow/issue/IN-1219/investigate-why-e2e-k8s-logs-are-missing-for-some-pods
* Some component logs are not showing  
* Not even getting collected
* For some that are collected, they are not in the compressed folder 
* The compressed logs have too many nested level folders
* Handle race condition caused by background processes being cut off by the blocking process if blocking process finishes quicker 
* Use the internal waiting mechanism `wait` that bash provides that can finish when all processes are done instead of waiting on our own blocking mechanism that waits only for last job
* This is needed only for K8 state collection and not stern component logs 
* This is because stern logs process is long running and wont need special waiting idioms 
* When unzipping …
> fix: resolve why k8 logs are missing:IN-1219

- src/commands/vfcli/vfcli-delete-or-release-env.yml
**Fixes or implements IN-1241**
Added command to free up environment after resetting its track
> fix: added a new command to free env (IN-1241)

- src/commands/vfcli/vfcli-delete-or-release-env.yml
**Fixes or implements IN-1265**
Update pipeline to add the `--no-circleci` flag 
> fix: introduced a flag to disable triggering circleCI build (IN-1265)

- src/executors/node/node-executor-node-20.yml
- src/jobs/e2e/collect-e2e-logs.yml
* Linear [ticket](https://linear.app/voiceflow/issue/IN-1271/add-events-to-e2e-logs) 
* Include kubernetes events in the gathered logs 
* Gather all events in the namespace except those from external-secrets and secret-store
* These doppler sync events are very verbose and are not relevant to the e2e tests
*  Kubernetes events have a ttl of 1 hr, return all relevant namespace events.Use jq to return actual timestamp of event so it can be corelated to service logs.
* The entries are then manipulated to return only the required fields in readable format
* This clean format is easier to read and useful in debugging, we dont want to return the entire JSON entry that represents an event as it has lots of unnecessary information that can slow down troubleshooting  
* …
> feat: add kubernetes events to logs:IN-1271

- src/commands/vfcli/vfcli-resetdb-free-env.yml
- src/jobs/e2e/resetdb-free-env.yml
**Fixes or implements IN-1321**
Added new command and job to reset database and free an env back into the pool
> feat: New command and job to reset database and free pool

- src/commands/track/update_database_track.yml
- src/commands/track/update_track.yml
- src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml
- src/jobs/e2e/provision-env.yml
- src/jobs/track/update_database_track.yml
- src/jobs/track/update_track.yml
- src/scripts/track/update_track.sh
This PR adds the following changes:
1. Refactor update database track job to use buildx
2. Add the ability to push or not a docker image using build
3. Add semantic override for database cli
4. fixes an issue with provision-env when force creating an environment
> feat: buildx for database-cli

- src/scripts/track/update_track.sh
Lift the arbitrary limitation that only `master` branch could push it's cache image to remote registry. This was only done initially as a safety mechanism not to let the repo size get out of control. 
- https://github.com/voiceflow/general-service/pull/600
> feat: any branch can push its cache (PL-000)

- src/commands/vfcli/vfcli-delete-or-release-env.yml
Remove duplicate release command
> fix: removed command that runs release twice

- src/executors/gomplate/gomplate-executor.yml
Add a smaller executor for running gomplate, otherwise you have to pull 500mb of node
Example of passing https://app.circleci.com/pipelines/github/voiceflow/creator-app/219910/workflows/f392ac40-fc86-4ae5-8b7c-a800c130a574
> Add an executor specifically for gomplate

- src/executors/node/e2e-executor.yml
- src/executors/node/smoke-executor.yml
Shaves ~30s off CI time because we don't have to re-pull every time.
See "already exists" messages here: https://app.circleci.com/pipelines/github/voiceflow/creator-app/219223/workflows/717dec82-a218-467d-adf9-cfb1cda3af90/jobs/950975
> Use new E2E image for smoke tests

- src/executors/node/node-executor-node-20.yml
This shaves 30 seconds off of the build step, because we can use the cached CircleCI layers
passing build: https://app.circleci.com/pipelines/github/voiceflow/creator-app/219904/workflows/5d6a1af6-9aa5-4a6e-a037-778ccdd2b6c7
> Use new node 20 image based off of CircleCI base image

- src/executors/node/default-executor-node-20.yml
- src/executors/node/default-executor.yml
This is one of the penultimate commits for the new images, by using circleCI's own docker images as a base, we can avoid re-pulling lots of data for every step of every pipeline.
> feat: Make default executor use new node image

- src/commands/yarn/yarn_command.yml
- src/scripts/yarn/run_command.sh
`trap` does not catch `ERR` when thrown in an `if` statement (or if it does, i'm just unsure of the flags to make it do so) since it would not cause the script to exit. This causes a long timeout in CI that are waiting on a success or failure signal. So I have added the failure signal (the existence of the file `/tmp/failure`) to the non-trap fail path as well.
> fix: trap failure (IN-1719)

- src/commands/vfcli/vfcli-suspend-env.yml
Wait for env suspension before making changes to deployment. Likely cause is Flux reverting deployment changes before it knows the env is suspended
> fix: wait on env suspension (IN-000)

- src/scripts/track/update_track.sh
Always need to create the track for gtmq_ tracks during update-track to be able to smoke test them. They don't exist until this point
> feat: update-track always creates gtmq_ track (IN-1727)

- src/jobs/e2e/collect-e2e-logs.yml
- src/jobs/e2e/prepare-env.yml
- src/jobs/e2e/provision-env.yml
- src/jobs/e2e/release-env.yml
- src/jobs/e2e/resetdb-free-env.yml
- src/jobs/e2e/run-e2e-tests.yml
* [Linear IN-1370](https://linear.app/voiceflow/issue/IN-1370/upgrade-kubernetes-clusters-from-v127-to-v130)
* Point vfcli  to use the latest Kubernetes v1.30 clusters 
> feat: switch to new v1.30 clusters:IN-1370

- src/executors/golang/go-executor.yml
* Linear [IN-1614](https://linear.app/voiceflow/issue/IN-1614/cloud-dependencies)
* Bump up golang version to 1.23 since the latest versions of our libraries need at least that version of go
* https://github.com/voiceflow/infracli/pull/107
* https://github.com/voiceflow/vfcli/pull/275
* https://github.com/voiceflow/warden/pull/75
* https://github.com/voiceflow/cloud/pull/111
> feat: update golang version for K8s v1.30 upgrade:IN-1614

- src/scripts/track/update_track.sh
There is an additional step for database-cli that was initially missed causing timeouts on provision-env. Instead of adding the gtmq logic to that command as well, i've updated `update_track` to write back to the sourced `/tmp/TRACK_EXISTS` so the logic is contained in one place. This value is again sourced by `update_database_track` but should now have the correct value
> fix: always create database track for gtmq (IN-1777)

- src/commands/github/create_commit_status.yml
- src/jobs/github/create_commit_status.yml
Create a GH Commit Status
Used to skip "Commit Status" checks that run for entering merge queue but shouldn't run on the merge queue branch, such as "UI Tests" in `react-chat` and `design` repos
> feat: skip GH Commit Status

- src/jobs/e2e/collect-e2e-logs.yml
Changes that weren't supposed to go in also broke the `stern` logging. This fixes by adding back in the redirect stdout to file
> fix: redirect stdout to file (IN-1855)

- src/jobs/smoke/report_smoke_failures.yml
fix: restore cache to get env_name.txt for report_smoke_failures. Otherwise it uses the ENV VAR, which is usually wrong.
Code copied from `collect-e2e-logs` jobs, verified by checking set cache from `src/commands/vfcli/vfcli-create-or-get-free-env-from-pool.yml`: 
```  - save_cache:
key: env_name_cache-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
paths:
- env_name.txt
```
> fix: restore cache to get env_name.txt for report_smoke_failures (IN-000)

- src/executors/node/playwright-executor.yml
playwright is now the bottleneck in our deployment pipeline, by about 2 minutes.
We have to raise the executor here before raising it in `automated-testing`, because if we increase the parallelism in `automated-testing`, all other repos will fail
> fix: bump playwright executor (RUN-476)

- src/jobs/smoke/report_smoke_failures.yml
So we can remove this alias and use the updated command name
https://github.com/voiceflow/automated-testing/blob/master/apps/test-cli/src/commands/report/index.ts#L3
> fix: use updated name for testcli report command (QLT-372)

- src/commands/monorepo/monorepo_lint_dockerfile.yml
- src/commands/utils/install_latest_hadolint.yml
Install the latest version of hadolint from github releases before running `monorepo_lint_dockerfile`
> feat: add command to install latest hadolint (IN-2335)

- src/scripts/track/update_track.sh
Add The DataDog Universal Service Tags and Git Repo Tags as image labels at build time. Doing so here standardizes across all services.
The same info as Env Vars can either be added in the Dockerfiles, and/or, at run time
Example in `general-service` with only a dev orb change: 
```
% BEFORE="168387678261.dkr.ecr.us-east-1.amazonaws.com/general-service:k8s-9deb190c4038afee230accfe34c179f7d22bff1c"
% AFTER="168387678261.dkr.ecr.us-east-1.amazonaws.com/general-service:k8s-d3b8f2246ec7bc8056ccae1e1eb10d830f157497"
% docker image inspect $BEFORE | jq -C '.[0].Config.Labels'
null
% docker image inspect $AFTER | jq -C '.[0].Config.Labels'
{
"com.datadoghq.tags.git.commit.sha": "",
"com.datadoghq.tags.git.repository_url": "git@github.com:voiceflow/general-service.git", …
```
> feat: add DataDog Universal Service Tags and git repo as image Labels (IN-2365)

- src/scripts/track/update_track.sh
`update_track` should respect the `UDPATE_TRACK_FILE` flag even for gtmq branches so that we can create the track in `create_manifest` where appropriate
> fix: only create a gtmq track if UPDATE_TRACK_FILE is also true (IN-2735)

- src/scripts/track/update_database_track.sh
We shouldn't need 2 different builder based on whether it is database cli or not. But this is a small fix to ensure track exists in update_database_track, as it's just a filename issue.
> fix: ensure track exists in update_database_track (IN-2761)

- .circleci/config.yml
Was missing the token for updating context
Test:
Before
After
> fix: use CIRCLE_TOKEN for circleci-cli orb update (IN-2754)

- src/scripts/track/promote_production.sh
Use the `master` tracks as the source of truth on the latest tag for a service. use the `tag` field to update `latest-production` tag, and copy the full track file to `production` track
> feat: use master tracks for tag and copy to production track (IN-3005)

- src/scripts/utils/check_wait_master.sh
Timing out would result in continuing the deployment instead of failing, results in deploying a previous version of master (from tracks)
> fix: fail on timeout waiting for master success (IN-3059)

- src/commands/track/update_database_track.yml
- src/commands/track/update_track.yml
- src/executors/node/code-test-executor-node-20.yml
- src/jobs/release/release.yml
- src/jobs/track/update_database_track.yml
- src/jobs/track/update_track.yml
- src/scripts/track/update_track.sh
This PR makes the following changes:
- Removes the `platform` parameter from track update commands and jobs
- only removes passing it through so we don't break workflows while deprecating this param
- rely on native architecture for platform instead of the flag
- Adds `node_version` parameter to database track commands and jobs
- Updates the `extra_build_args` to use the node version parameter
- Adds `pre_release_steps` parameter to the release job
- Updates Docker images in the Node 20 executor:
- Changes `circleci/redis:6.2-alpine` to `cimg/redis:6.2`
- Changes `circleci/mongo:4.4.1` to `mongo:4.4.1`
- Simplifies Docker buildx creation by removing platform specification and using `--bootstrap` flag
- dependency of https://github.com/voiceflow/canvas-export/pull/254
- dependency of …
> chore: remove platform as param for update_track (IN-3157)

- src/scripts/track/update_track.sh
Added GitHub token as a build secret to the track update script. 
Added a new `BUILD_SECRETS` array to the `update_track.sh` script that includes the `GITHUB_TOKEN` as an environment variable secret. This secret is now passed to the `docker buildx build` command. Leaving the build arg in this phase as we move to deprecate it. 
This change allows the Docker build process to securely access GitHub resources that require authentication, such as private repositories or packages, without exposing the token in the build arguments or image layers. Using the `--secret` flag ensures the token is only available during build time and not persisted in the final image.
> feat: GITHUB_TOKEN as build secret (IN-3193)
